name: Check format and lint
on: 
  push:
  workflow_dispatch:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Note that you must checkout your code before running haskell-actions/run-fourmolu
      - uses: actions/checkout@v3
      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "latest"
