name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.4.7'
        cabal-version: '3.10.1.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: |
          ~/.cache/cabal
          ~/.config/cabal
          ~/.local/state/cabal
          ~/.local/bin
          dist-newstyle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build
          ${{ runner.os }}

    - name: Install dependencies
      run: |
        cabal v2-build  --disable-tests --disable-benchmarks --dependencies-only -j2 all
        cabal v2-build  --enable-tests --enable-benchmarks --dependencies-only -j2 all
    - name: Build w/o tests
      run: |
        cabal v2-build  --disable-tests --disable-benchmarks all
    - name: Build
      run: |
        cabal v2-build  --enable-tests --enable-benchmarks all --write-ghc-environment-files=always
    - name: Tests
      run: |
        cabal v2-test  --enable-tests --enable-benchmarks all --test-show-details=direct  -- --xml=junit.xml
    - name: Run benchmarks
      run: cabal run benchmarks -- --junit bench.xml
    - name: Cabal check
      run: |
        cabal -vnormal check
    - name: haddock
      run: |
        cabal v2-haddock --disable-documentation --haddock-all --enable-tests --enable-benchmarks all
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          *.xml