name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.6.3'
        cabal-version: '3.10.1.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: |
          ~/.cache/cabal
          ~/.config/cabal
          ~/.local/state/cabal
          ~/.local/bin
          dist-newstyle
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build
          ${{ runner.os }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal configure --enable-tests --enable-benchmarks && cabal run tests -- --xml=junit.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          .xml