name: Check license headers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check licenses
        run: wget https://github.com/vaclavsvejcar/headroom/releases/download/v0.4.3.0/headroom-0.4.3.0-Linux-ghc-8.10.4 -O headroom && chmod +x headroom && ./headroom run -c

