name: Lint code
on: 
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
  workflow_dispatch:

jobs:
  hlint:
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/hlint-scan@v1
