name: Static analysis

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  build:
    name: ghc-${{ matrix.ghc }} z3-${{ matrix.z3 }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.1.0"]
        ghc:
          - "9.4.7"
        z3:
          - "4.10.2"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup z3-4.10.2
        uses: pavpanchekha/setup-z3@6b2d476d7a9227e0d8d2b94f73cd9fcba91b5e98
        with:
          version: ${{ matrix.z3 }}

      - name: Workaround runner image issue
        run: sudo chown -R $USER /usr/local/.ghcup

      - name: Setup GHC and cabal-install
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            ~/.local/bin
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}

      - name: Update package list
        run: cabal update

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks --flags="stan" all
      - name: Build stan
        run: 'type -P "stan" || pushd /tmp && git clone https://github.com/kowainik/stan.git && cd stan && cabal v2-build exe:stan && mkdir -p ~/.local/bin &&  cp "$(cabal v2-exec --verbose=0 --offline sh -- -c "command -v stan")" ~/.local/bin/stan && popd'
      - name: Run stan
        run: stan