name: Static analysis

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  build:
    name: ghc-${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.1.0"]
        ghc:
          - "9.4.7"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Workaround runner image issue
        run: sudo chown -R $USER /usr/local/.ghcup

      - name: Setup GHC and cabal-install
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            ~/.local/bin
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}

      - name: Update package list
        run: cabal update

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks --flags="stan" all
      - name: Build stan
        run: cabal v2-install stan --install-method=copy --overwrite-policy=always
      - name: Run stan
        run: stan
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: stan.html